---
- name: Simple Ansible Playbook for Windows
  hosts: 4.231.114.250
  gather_facts: false
  tasks:
    - name: Run a command on Windows
      win_shell: |
        # Replace this with the actual command you want to run
        Write-Host "Hello from Ansible on Windows!"
      register: command_output

    - name: Display command output
      debug:
        var: command_output.stdout_lines
